const apiBaseUrl = (process.env['API_BASE_URL'] ?? 'http://127.0.0.1:3100').replace(/\/+$/, '');
const ownerHeaders = devHeaders('ci-owner', 'CI Owner');
const memberHeaders = devHeaders('ci-member', 'CI Member');
const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

await expectJson('GET', '/health', undefined, undefined, 200, (body) => {
  assert(body.status === 'ok', 'Health endpoint did not report ok.');
  assert(body.database === 'memory', 'Health endpoint did not report memory persistence.');
});

await expectJson('GET', '/rooms', undefined, undefined, 200, (body) => {
  assert(Array.isArray(body), 'Rooms response must be an array.');
});

await expectJson('GET', '/houses', undefined, undefined, 200, (body) => {
  assert(Array.isArray(body), 'Houses response must be an array.');
});

const standalone = await expectJson(
  'POST',
  '/rooms',
  { title: 'CI Standalone Room' },
  ownerHeaders,
  201,
  (body) => {
    assert(body.participant === undefined, 'Room creation response must remain actor-neutral.');
    assert(uuidPattern.test(body.room?.id ?? ''), 'Room id must be a server-generated UUID.');
    assert(body.room?.slug === 'ci-standalone-room', 'Room slug was not generated from the title.');
    assert(body.room?.title === 'CI Standalone Room', 'Room title was not preserved.');
    assert(body.room?.participants?.[0]?.role === 'owner', 'Standalone room owner was not persisted.');
  },
);

await expectStatus(
  'POST',
  '/rooms',
  { title: 'CI Standalone Room' },
  ownerHeaders,
  409,
);

await expectJson(
  'POST',
  '/rooms/join',
  { roomId: standalone.room.slug },
  ownerHeaders,
  201,
  (body) => {
    assert(body.roomId === standalone.room.id, 'Join session did not resolve the immutable room id.');
    assert(body.roomSlug === standalone.room.slug, 'Join session did not preserve the route slug.');
    assert(body.roomTitle === standalone.room.title, 'Join session did not preserve the display title.');
    assert(body.participant?.role === 'owner', 'Owner role was not restored on join.');
    assert(typeof body.token === 'string' && body.token.length > 0, 'Join session did not issue a token.');
  },
);

const createdHouse = await expectJson(
  'POST',
  '/houses',
  { name: 'CI House', description: 'Compiled API smoke test.' },
  ownerHeaders,
  201,
  (body) => {
    assert(uuidPattern.test(body.house?.id ?? ''), 'House id must be a UUID.');
    assert(body.role === 'owner', 'House creator must be the owner.');
  },
);

await expectJson(
  'GET',
  `/houses/${encodeURIComponent(createdHouse.house.id)}`,
  undefined,
  undefined,
  200,
  (body) => {
    assert(body.role === null, 'Public House read must not invent an authenticated role.');
    assert(body.house?.name === 'CI House', 'Public House read returned the wrong House.');
  },
);

await expectJson(
  'POST',
  '/houses/join',
  { houseId: createdHouse.house.id },
  memberHeaders,
  201,
  (body) => {
    assert(body.role === 'member', 'Joining a House must create a member role.');
  },
);

await expectJson(
  'GET',
  `/houses/${encodeURIComponent(createdHouse.house.id)}`,
  undefined,
  memberHeaders,
  200,
  (body) => {
    assert(body.role === 'member', 'Authenticated House read did not resolve membership.');
  },
);

await expectJson(
  'POST',
  `/houses/${encodeURIComponent(createdHouse.house.id)}/rooms`,
  { title: 'CI House Room' },
  ownerHeaders,
  201,
  (body) => {
    assert(uuidPattern.test(body.room?.id ?? ''), 'House room id must be a server-generated UUID.');
    assert(body.room?.slug === 'ci-house-room', 'House room slug was not generated by the server.');
    assert(body.room?.title === 'CI House Room', 'House room title was not preserved.');
  },
);

console.log('✓ Compiled API behavior smoke tests passed');

function devHeaders(userId, displayName) {
  return {
    'x-dev-user-id': userId,
    'x-dev-display-name': displayName,
  };
}

async function expectStatus(method, path, body, headers, expectedStatus) {
  const response = await request(method, path, body, headers);
  assert(
    response.status === expectedStatus,
    `${method} ${path} expected ${expectedStatus}, received ${response.status}: ${await response.text()}`,
  );
}

async function expectJson(method, path, body, headers, expectedStatus, validate) {
  const response = await request(method, path, body, headers);
  const text = await response.text();
  assert(
    response.status === expectedStatus,
    `${method} ${path} expected ${expectedStatus}, received ${response.status}: ${text}`,
  );

  let parsed;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    throw new Error(`${method} ${path} returned invalid JSON: ${text}`);
  }

  validate(parsed);
  return parsed;
}

function request(method, path, body, headers = {}) {
  return fetch(`${apiBaseUrl}${path}`, {
    method,
    headers: {
      ...headers,
      ...(body === undefined ? {} : { 'content-type': 'application/json' }),
    },
    ...(body === undefined ? {} : { body: JSON.stringify(body) }),
  });
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}
